/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user (customer) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Social Login */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all staff members */
        get: operations["listStaff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["listCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["listCategories"];
        put?: never;
        /** Create new category */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all menu items */
        get: operations["listMenuItems"];
        put?: never;
        /** Create menu item */
        post: operations["createMenuItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allergens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all allergens */
        get: operations["listAllergens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders */
        get: operations["listOrders"];
        put?: never;
        /** Place a new order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order details */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all restaurant tables */
        get: operations["listTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tables/{tableId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update table status */
        patch: operations["updateTableStatus"];
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reservations */
        get: operations["listReservations"];
        put?: never;
        /** Create a reservation */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process payment for an order */
        post: operations["processPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts/{receiptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get receipt details */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales analytics */
        get: operations["getSalesAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer analytics (repeat customers, retention) */
        get: operations["getCustomerAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/top-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get top selling menu items */
        get: operations["getTopItemsAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    newOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Broadcast new order to Kitchen (STOMP /topic/orders/new) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            responses: {
                /** @description Event broadcasted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    orderStatusUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Broadcast order status update (STOMP /topic/orders/{id}/status) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            responses: {
                /** @description Event broadcasted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    tableStatusUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Broadcast table status update (STOMP /topic/tables/status) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RestaurantTable"];
                };
            };
            responses: {
                /** @description Event broadcasted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        Auditable: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            version?: number;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            fullName: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            user?: components["schemas"]["User"];
        };
        Permission: {
            id?: number;
            name?: string;
            description?: string;
        };
        Role: {
            id?: number;
            name?: string;
            description?: string;
            permissions?: components["schemas"]["Permission"][];
        };
        User: components["schemas"]["Auditable"] & {
            id?: number;
            /** Format: email */
            email?: string;
            fullName?: string;
            phone?: string;
            enabled?: boolean;
            /** @enum {string} */
            provider?: "LOCAL" | "GOOGLE";
            providerId?: string;
            roles?: components["schemas"]["Role"][];
        };
        Staff: components["schemas"]["Auditable"] & {
            id?: number;
            user?: components["schemas"]["User"];
            employeeCode?: string;
            /** Format: date */
            hireDate?: string;
            active?: boolean;
        };
        Customer: components["schemas"]["Auditable"] & {
            id?: number;
            user?: components["schemas"]["User"];
            loyaltyPoints?: number;
            /** Format: date-time */
            lastVisit?: string;
        };
        Allergen: {
            id?: number;
            name?: string;
        };
        MenuItem: components["schemas"]["Auditable"] & {
            id?: number;
            nameNl?: string;
            nameEn?: string;
            descriptionNl?: string;
            descriptionEn?: string;
            /** Format: double */
            price?: number;
            imageUrl?: string;
            available?: boolean;
            featured?: boolean;
            prepTimeMinutes?: number;
            calories?: number;
            categoryId?: number;
            categoryNameNl?: string;
            categoryNameEn?: string;
            allergens?: components["schemas"]["Allergen"][];
        };
        Category: components["schemas"]["Auditable"] & {
            id?: number;
            nameNl?: string;
            nameEn?: string;
            icon?: string;
            sortOrder?: number;
            active?: boolean;
            items?: components["schemas"]["MenuItem"][];
        };
        CreateMenuItemRequest: {
            nameNl: string;
            nameEn: string;
            descriptionNl?: string;
            descriptionEn?: string;
            /** Format: double */
            price: number;
            categoryId: number;
            imageUrl?: string;
            prepTimeMinutes?: number;
            allergensIds?: number[];
        };
        OrderItem: {
            id?: number;
            quantity?: number;
            /** Format: double */
            unitPrice?: number;
            specialRequest?: string;
            /** @enum {string} */
            status?: "PENDING" | "PREPARING" | "READY" | "SERVED" | "CANCELLED";
            menuItem?: components["schemas"]["MenuItem"];
        };
        Order: components["schemas"]["Auditable"] & {
            id?: number;
            orderNumber?: string;
            /** @enum {string} */
            type?: "DINE_IN" | "TAKEAWAY" | "DELIVERY";
            /** @enum {string} */
            status?: "PENDING" | "PREPARING" | "READY" | "SERVED" | "PAID" | "CANCELLED";
            /** Format: double */
            subtotal?: number;
            /** Format: double */
            tax?: number;
            /** Format: double */
            discount?: number;
            /** Format: double */
            total?: number;
            customerNote?: string;
            table?: components["schemas"]["RestaurantTable"];
            assignedWaiter?: components["schemas"]["Staff"];
            customer?: components["schemas"]["Customer"];
            items?: components["schemas"]["OrderItem"][];
            payment?: components["schemas"]["Payment"];
        };
        PlaceOrderRequest: {
            /** @enum {string} */
            orderType: "DINE_IN" | "TAKEAWAY" | "DELIVERY";
            tableId?: number;
            customerId?: number;
            items: {
                menuItemId: number;
                quantity: number;
                specialRequest?: string;
            }[];
        };
        RestaurantTable: components["schemas"]["Auditable"] & {
            id?: number;
            tableNumber?: string;
            capacity?: number;
            /** @enum {string} */
            section?: "MAIN" | "PATIO" | "BAR" | "PRIVATE";
            /** @enum {string} */
            status?: "AVAILABLE" | "OCCUPIED" | "RESERVED";
        };
        Reservation: components["schemas"]["Auditable"] & {
            id?: number;
            /** Format: date-time */
            reservationTime?: string;
            partySize?: number;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "NO_SHOW" | "COMPLETED";
            customer?: components["schemas"]["Customer"];
            table?: components["schemas"]["RestaurantTable"];
        };
        CreateReservationRequest: {
            /** Format: date-time */
            reservationTime: string;
            partySize: number;
            customerId: number;
            tableId?: number;
        };
        Payment: components["schemas"]["Auditable"] & {
            id?: number;
            /** @enum {string} */
            method?: "CASH" | "CARD" | "MOBILE" | "ONLINE";
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED" | "FAILED" | "REFUNDED";
            /** Format: double */
            amount?: number;
            stripePaymentIntentId?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        ProcessPaymentRequest: {
            orderId: number;
            /** @enum {string} */
            method: "CASH" | "CARD" | "MOBILE" | "ONLINE";
            /** Format: double */
            amount?: number;
        };
        Receipt: {
            id?: number;
            receiptNumber?: string;
            pdfUrl?: string;
            /** Format: date-time */
            issuedAt?: string;
            payment?: components["schemas"]["Payment"];
        };
        SalesAnalytics: {
            /** Format: double */
            totalRevenue?: number;
            totalOrders?: number;
            /** Format: double */
            averageOrderValue?: number;
            dateRange?: string;
        };
        CustomerAnalytics: {
            totalCustomers?: number;
            newCustomers?: number;
            repeatCustomers?: number;
            /** Format: double */
            retentionRatePercentage?: number;
        };
        TopMenuItem: {
            menuItemId?: number;
            name?: string;
            quantitySold?: number;
            /** Format: double */
            revenue?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful registration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Tokens refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Successful login via Google */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of staff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"][];
                };
            };
        };
    };
    listCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"][];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories with nested menu items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    icon?: string;
                    sortOrder?: number;
                };
            };
        };
        responses: {
            /** @description Category created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    listMenuItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of menu items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"][];
                };
            };
        };
    };
    createMenuItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMenuItemRequest"];
            };
        };
        responses: {
            /** @description Menu item created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"];
                };
            };
        };
    };
    listAllergens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of allergens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allergen"][];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                status?: "PENDING" | "PREPARING" | "READY" | "SERVED" | "PAID" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOrderRequest"];
            };
        };
        responses: {
            /** @description Order created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "PENDING" | "PREPARING" | "READY" | "SERVED" | "PAID" | "CANCELLED";
                };
            };
        };
        responses: {
            /** @description Order status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    listTables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantTable"][];
                };
            };
        };
    };
    updateTableStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "AVAILABLE" | "OCCUPIED" | "RESERVED";
                };
            };
        };
        responses: {
            /** @description Table status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantTable"];
                };
            };
        };
    };
    listReservations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of reservations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description Reservation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    processPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPaymentRequest"];
            };
        };
        responses: {
            /** @description Payment processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receiptId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receipt details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
        };
    };
    getSalesAnalytics: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sales analytics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesAnalytics"];
                };
            };
        };
    };
    getCustomerAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer analytics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerAnalytics"];
                };
            };
        };
    };
    getTopItemsAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top items retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopMenuItem"][];
                };
            };
        };
    };
}
